apiVersion: backstage.io/v1alpha1
kind: Location

metadata:
  name: pos-platform

spec:
  targets:
    - ./group.yaml
    - ./system.yaml
    - ./pos-web.yaml
    - ./pos-api.yaml
    - ./auth-service.yaml
    - ./notification-service.yaml
    - ./pos-api-definition.yaml
