apiVersion: backstage.io/v1alpha1
kind: API

metadata:
  name: pos-api

spec:
  type: openapi

  lifecycle: production

  owner: engineering

  definition: |
    openapi: 3.0.0apiVersion: backstage.io/v1alpha1
kind: Component

metadata:
  name: pos-api-service

  annotations:
    github.com/project-slug: thevaibhavbhatnagar/pos-api

spec:
  type: service
  lifecycle: production
  owner: engineering

  system: pos-platform

  providesApis:
    - pos-api
    info:
      title: POS API
      version: 1.0.0