apiVersion: backstage.io/v1alpha1
kind: Component

metadata:
  name: pos-api-service

  annotations:
    github.com/project-slug: thevaibhavbhatnagar/pos-api

spec:
  type: service
  lifecycle: production
  owner: engineering
  system: pos-platform

  providesApis:
    - pos-api